theme = "modern"
icons = "awesome"

[[block]]
block = "music"
buttons = ["play", "next"]

[[block]]
block = "cpu"
interval = 1

[[block]]
block = "memory"
display_type = "memory"
format_mem = "{Mup}%"
format_swap = "{SUp}%"

[[block]]
block = "sound"

[[block]]
block = "uptime"

[[block]]
block = "weather"
format = "{weather} {temp}°"
service = { name = "openweathermap", api_key = "42a5ba1763b50006babed87fb21ac824", city_id = "3827414", units = "metric" }

[[block]]
block = "time"
interval = 1
format = "%a %d/%m/%Y %H:%M:%S"
